//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Faker.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Beer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Beer() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Faker.Resources.Beer", typeof(Beer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ahtanum;Amarillo;Bitter Gold;Bravo;Brewer’s Gold;Bullion;Cascade;Cashmere;Centennial;Chelan;Chinook;Citra;Cluster;Columbia;Columbus;Comet;Crystal;Equinox;Eroica;Fuggle;Galena;Glacier;Golding;Hallertau;Horizon;Liberty;Magnum;Millennium;Mosaic;Mt. Hood;Mt. Rainier;Newport;Northern Brewer;Nugget;Olympic;Palisade;Perle;Saaz;Santiam;Simcoe;Sorachi Ace;Sterling;Summit;Tahoma;Tettnang;TriplePearl;Ultra;Vanguard;Warrior;Willamette;Yakima Gol.
        /// </summary>
        internal static string Hop {
            get {
                return ResourceManager.GetString("Hop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black malt;Caramel;Carapils;Chocolate;Munich;Caramel;Carapils;Chocolate malt;Munich;Pale;Roasted barley;Rye malt;Special roast;Victory;Vienna;Wheat mal.
        /// </summary>
        internal static string Malt {
            get {
                return ResourceManager.GetString("Malt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pliny The Elder;Founders Kentucky Breakfast;Trappistes Rochefort 10;HopSlam Ale;Stone Imperial Russian Stout;St. Bernardus Abt 12;Founders Breakfast Stout;Weihenstephaner Hefeweissbier;Péché Mortel;Celebrator Doppelbock;Duvel;Dreadnaught IPA;Nugget Nectar;La Fin Du Monde;Bourbon County Stout;Old Rasputin Russian Imperial Stout;Two Hearted Ale;Ruination IPA;Schneider Aventinus;Double Bastard Ale;90 Minute IPA;Hop Rod Rye;Trappistes Rochefort 8;Chimay Grande Réserve;Stone IPA;Arrogant Bastard Ale;Edmund Fitzg [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Lager;Pilsner;European Amber Lager;Dark Lager;Bock;Light Hybrid Beer;Amber Hybrid Beer;English Pale Ale;Scottish And Irish Ale;Merican Ale;English Brown Ale;Porter;Stout;India Pale Ale;German Wheat And Rye Beer;Belgian And French Ale;Sour Ale;Belgian Strong Ale;Strong Ale;Fruit Beer;Vegetable Beer;Smoke-flavored;Wood-aged Beer.
        /// </summary>
        internal static string Style {
            get {
                return ResourceManager.GetString("Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 007 - German Ale;1010 - American Wheat;1028 - London Ale;1056 - American Ale;1084 - Irish Ale;1098 - British Ale;1099 - Whitbread Ale;1187 - Ringwood Ale;1272 - American Ale II;1275 - Thames Valley Ale;1318 - London Ale III;1332 - Northwest Ale;1335 - British Ale II;1450 - Dennys Favorite 50;1469 - West Yorkshire Ale;1728 - Scottish Ale;1968 - London ESB Ale;2565 - Kölsch;1214 - Belgian Abbey;1388 - Belgian Strong Ale;1762 - Belgian Abbey II;3056 - Bavarian Wheat Blend;3068 - Weihenstephan Weizen;3278 - Bel [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Yeast {
            get {
                return ResourceManager.GetString("Yeast", resourceCulture);
            }
        }
    }
}
